# Generated by Django 5.0.3 on 2024-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('PC', 'Phones and Computer Accessories'), ('MW', 'Men and Women Fashion'), ('SC', 'Skin Care')], max_length=2),
        ),
    ]
